version: "3.9"

services:
  db:
    image: postgres:15
    container_name: usabit_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usabit_db
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    container_name: usabit_api
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
